/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Maxime Gerardin (https://sketchfab.com/maximegerardincontact)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-set-15daf94ae5c74e1282c0a97ac9dd0f29
Title: Chess Set
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function BlackKnight(props) {
  const { nodes, materials } = useGLTF("/models/glass.glb")
  return (
    <group {...props} dispose={null}>
      <group scale={0.05} position={[0, 0.86, 0.1]} rotation={[0, 3, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Piece_03003_Black_Player001_0.geometry}
          material={materials["Black_Player.001"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/glass.glb")
